replicaCount: 2

nginxReplicaCount: 1

imageTag: v0.0.1

config:
  path: "/etc/caster"
  port: 2376

  caster:
    debug: false
    capacity: 16384

  nginx:
    workerConnections: 16384

  tracer:
    fraction: 1
    jaegerAgent:
      host: jaeger-svc
      port: 6831
