replicaCount: 2

nginxReplicaCount: 1

imageTag: v0.0.2

config:
  path: "/etc/caster"
  port: 2376

  caster:
    debug: false
    capacity: 16384

  nginx:
    workerConnections: 16384

  tracer:
    fraction: 1
    collectorAddress: "http://jaeger-svc:14268/api/traces"
