apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels: {{ toYaml .Values.configMap.labels | nindent 4 }}
data:
  {{ .Values.configMap.key }}: {{ .Values.configMap.value | nindent 4 }}
