apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    name: jaeger
    app: jaeger-all-in-one
spec:
  selector:
    matchLabels:
      name: jaeger
      app: jaeger-all-in-one
  replicas: 1
  template:
    metadata:
      name: jaeger
      app: jaeger-all-in-one
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.47
          ports:
            - containerPort: 5775
              protocol: UDP
            - containerPort: 6831
              protocol: UDP
            - containerPort: 6832
              protocol: UDP
            - containerPort: 5778
              protocol: TCP
            - containerPort: 16686
              protocol: TCP
            - containerPort: 14250
              protocol: TCP
            - containerPort: 14268
              protocol: TCP
            - containerPort: 14269
              protocol: TCP
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 9411
              protocol: TCP
          env:
            - name: COLLECTOR_ZIPKIN_HTTP_PORT
              value: 9411
          resources:
            limits:
              memory: 200Mi
              cpu: 200m
