apiVersion: apps/v1
kind: Deployment
metadata:
  name: caster-nginx
  labels:
    app: caster-nginx
    name: caster-nginx
spec:
  selector:
    matchLabels:
      app: caster-nginx
      name: caster-nginx
  replicas: {{ .Values.nginxReplicaCount }}
  template:
    metadata:
      labels:
        app: caster-nginx
        name: caster-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25
          ports:
            - name: http
              containerPort: {{ $.Values.config.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/nginx
              readOnly: true
            - name: log
              mountPath: /var/log/nginx
          resources:
            limits:
              memory: 100Mi
              cpu: 100m
      volumes:
        - name: config
          configMap:
            name: caster-nginx-config
        - name: log
          emptyDir: {}
