{{- range $i := until (.Values.replicaCount|int) }}
apiVersion: v1
kind: Pod
metadata:
  name: caster-pod-{{ $i }}
  labels:
    app: caster
    name: caster-pod-{{ $i }}
spec:
  containers:
    - name: caster
      image: mojixcoder/caster:{{ $.Values.imageTag }}
      command:
        - ./caster
        - run
        - --config
        - {{ $.Values.config.path }}
      ports:
        - name: http
          containerPort: {{ $.Values.config.port }}
          protocol: TCP
      volumeMounts:
        - name: config
          mountPath: {{ $.Values.config.path }}
          readOnly: true
      resources:
        limits:
          memory: 100Mi
          cpu: 100m
  volumes:
    - name: config
      configMap:
        name: caster-config-{{ $i }}

---
{{- end }}
