name: Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"

    steps:
      - name: Get tag
        run: echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: mojixcoder/caster:${{ env.TAG }}
    